### ISSUE TITLE
UserId Where can i see userId? thanks

### ISSUE THREAD

**Issue by datcorona** [rytr-me/documentation#4]
Where can i see userId? thanks

**Comment by atulmy** [comment]
As documented here https://github.com/rytr-me/documentation#ryte, 
For userId you need to supply user ID from your database, eg: primary key for users database table. As a consumer of Rytr API, we assume you have a product/service yourself with user, hence since they'll be exposed to the API via your service, we need to track a unique key for each user from your database. It doesn't necessarily need to be a primary key, it can be any unique key generated for each user.
